### ISSUE TITLE
Provide option to skip remote check if deploy lifecycle is not executed

### ISSUE THREAD

**Issue by mseele** [chonton/exists-maven-plugin#30]
We have a parent pom with our intranet maven repository that can only be deployed from a specific build server. We use `exists-maven-plugin` to avoid duplicate deployments.

When we run `mvn install` the `exists-maven-plugin` always try to execute its `remote` task and fails because the intranet maven repository path is not available on a local machine.

It would be cool if we can configure that the `remote` task should only be executed if the `deploy` lifecycle is in the executed lifecycles. It makes no sense to run the `remote` task if the deploy lifecycle is not executed.

**Comment by chonton** [comment]
By default, the _remote_ goal is bound to the _verify_ phase.  To work as expected, this goal must be executed before the maven-deploy-plugin's _deploy_ goal, which is bound to the _deploy_ phase.  You could change the binding of the _remote_ goal to the _deploy_ phase with the following:
```
      <plugin>
        <groupId>org.honton.chas</groupId>
        <artifactId>exists-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>remote</goal>
            </goals>
              <phase>deploy</phase>
          </execution>
        </executions>
      </plugin>
```
However, the _deploy_ goal will still run first because ["When multiple executions are given that match a particular phase, they are executed in the order specified in the POM, with inherited executions running first."](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#plugins).

My recommendation is to wrap the exists-maven-plugin in a profile that is activated only in the build host
```
  <profiles>
    <profile>
      <id>deploy-only-on-specific-host</id>
      <activation>
        <property>
          <name>build-server</name>
          <value>name</value>
        </property>
      </activation>
      <build>
        <plugin>
          <groupId>org.honton.chas</groupId>
          <artifactId>exists-maven-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>remote</goal>
              </goals>
                <phase>deploy</phase>
            </execution>
          </executions>
        </plugin>
      </build>
    </profile>
  </profiles>
```
